# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obi-store-demo
images:
- name: obi-store-demo-adservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-adservice
- name: obi-store-demo-cartservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-cartservice
- name: obi-store-demo-checkoutservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-checkoutservice
- name: obi-store-demo-currencyservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-currencyservice
- name: obi-store-demo-emailservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-emailservice
- name: obi-store-demo-frontend
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-frontend
- name: obi-store-demo-loadgenerator
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-loadgenerator
- name: obi-store-demo-paymentservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-paymentservice
- name: obi-store-demo-productcatalogservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-productcatalogservice
- name: obi-store-demo-recommendationservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-recommendationservice
- name: obi-store-demo-shippingservice
  newName: image-registry.openshift-image-registry.svc:5000/obi-store-demo/obi-store-demo-shippingservice

patches:
- path: patch-openshift-securitycontext.yaml
  target:
    kind: Deployment

resources:
- 00-namespace.yaml
- 01-observability.yaml
- adservice.yaml
- cartservice.yaml
- checkoutservice.yaml
- currencyservice.yaml
- emailservice.yaml
- frontend.yaml
- loadgenerator.yaml
- paymentservice.yaml
- productcatalogservice.yaml
- recommendationservice.yaml
- shippingservice.yaml
